### ISSUE TITLE
Texture reference in MTL files is incorrect

### ISSUE THREAD

**Issue by Xenation** [KayKit-Game-Assets/KayKit-Dungeon-Remastered-1.0#1]
The materials for `.obj` files (`.mtl`) have an incorrect path for the texture. The path is an absolute path from your computer's directory structure, and as such does not point to any file on other computers.
The line:
`map_Kd C:\\Users\\Kay Lousberg\\Desktop\\Work\\Gameassets\\Kay Lousberg Assets\\KayKit\\Master Maker Files\\2023 Remake - Textured\\3. Dungeon Asset Pack\\Export Files\\export 1.0\\standard\\texture\\dungeon_texture.png`
should probably be:
`map_Kd ..\\texture\\dungeon_texture.png`

I made a script to fix my files locally, so maybe I could fork and do a pull request with the fixed files.

**Comment by KayKit-Game-Assets** [comment]
Hey, thanks for the heads up. 

Should be fixed now!
